on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-prerelease[0-9][0-9][0-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
#    - name: Verify commit exists in origin/main
#      run: |
#        git fetch --no-tags --prune --depth=1 origina +refs/heads/*:refs/remotes/origin*
#        git branch --remote --contains | grep origin/main
    - name: Set version variable tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build the package
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Execute tests
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack the package
      run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --ouput .
    - name: Push package
      run: dotnet nuget push Evergrowth.AspForMarkDigExtension.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY)
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
